//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndCalculator
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int InputOut = 2131034112;
			
			// aapt resource value: 0x7f050011
			public const int buttonCE = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int buttonDivide = 2131034132;
			
			// aapt resource value: 0x7f05000d
			public const int buttonEight = 2131034125;
			
			// aapt resource value: 0x7f050013
			public const int buttonEquile = 2131034131;
			
			// aapt resource value: 0x7f050008
			public const int buttonFive = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int buttonFour = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int buttonMinus = 2131034122;
			
			// aapt resource value: 0x7f05000f
			public const int buttonMulti = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int buttonNine = 2131034126;
			
			// aapt resource value: 0x7f050002
			public const int buttonOne = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int buttonPlus = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int buttonSeven = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int buttonSix = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int buttonThree = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int buttonTwo = 2131034115;
			
			// aapt resource value: 0x7f050012
			public const int buttonZero = 2131034130;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int linearLayout2 = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int linearLayout3 = 2131034123;
			
			// aapt resource value: 0x7f050010
			public const int linearLayout4 = 2131034128;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
